adds ability to stream logs to loki

diff --git a/kube-gcp-updater b/kube-gcp-updater
--- a/kube-gcp-updater
+++ b/kube-gcp-updater
@@ -19,6 +19,9 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
+# Static vars
+LOG_FILE='kube-updater.log'
+
 readonly retire_time=$(date +"%Y-%m-%dT%H-%M-%SZ")
 
 # flags
@@ -27,26 +30,29 @@ gcp_project=''
 role=''
 resume=''
 timeout=600
+promtail_cfg=''
 
 usage() {
   cat <<EOF
 Usage: $0 -c <kube_context> -p <gcp_project> -s [retire_time_label] -r [role]
-        -t [timeout]
+        -t [timeout] -l [promtail_cfg]
 
   -s    Resume node rolling. Argument is retire_time label. If set, -r [role]
         must also be set
   -t    Node drain timeout. How long to wait for the node to drain before
         shutting it down (in seconds, default 300s)
+  -l    Path to promtail config (when set stdout will be streamed to loki by proxy of a log file)
 EOF
 }
 
-while getopts 'c:p:r:hs:t:' flag; do
+while getopts 'c:p:r:hs:t:l:' flag; do
   case "${flag}" in
     c) kube_context="${OPTARG}" ;;
     p) gcp_project="${OPTARG}" ;;
     r) role="${OPTARG}" ;;
     s) resume="${OPTARG}" ;;
     t) timeout="${OPTARG}" ;;
+    l) promtail_cfg="${OPTARG}" ;;
     h) usage && exit 0 ;;
     *) echo "Unexpected option: ${flag}" && usage && exit 1 ;;
   esac
@@ -96,6 +102,21 @@ fi
 
 # Verify we can successfully authenticate with Google
 gcloud projects describe "${gcp_project}"
+
+# Cleanup child processes on exit
+trap "kill 0" EXIT
+
+if [[ -n "${promtail_cfg}" ]]; then
+  if ! command -v promtail &> /dev/null; then
+    echo "Promtail not installed"
+    exit 1
+  fi
+
+  promtail --config.file="${promtail_cfg}" --client.external-labels=context="${kube_context}",host="$(hostname)" &
+  touch "${LOG_FILE}"
+  sleep 2 # give promtail time to start
+  exec &> >(tee "${LOG_FILE}") # redirect execution through tee
+fi
 
 function fail() {
   echo $1 >&2
